### ISSUE TITLE
error: redeclaration of ‘IMREAD_UNCHANGED’

### ISSUE THREAD

**Issue by chfakht** [benhoff/face-recognizer-gui#6]
Hi ,
when running make i get the following errors

usr/local/include/opencv2/highgui/highgui.hpp:165:5: note: previous declaration ‘cv::<anonymous enum> IMREAD_UNCHANGED’
/usr/local/include/opencv2/imgcodecs.hpp error: redeclaration of ‘IMREAD_GRAYSCALE’
/usr/local/include/opencv2/imgcodecs.hpp error: redeclaration of ‘IMREAD_COLOR’
/usr/local/include/opencv2/imgcodecs.hpp:70:28: error: redeclaration of ‘IMREAD_ANYDEPTH’
there are plenty of them
i think the problem is that i have installed firstly opencv 3.0.0 alpha and  i want to change it to opencv 2.4.10 so what i have did is deleting manually all libraries and headers in /usr/local/lib and /usr/local/include (that because i haven't found a tutorial explaining how to properly delete opencv or re-install it) and after that i installed opencv 2.4.10
that's is the source of the error but now how can i solve this ??
Any suggestion will be appreciated :)
NB : I'm using ubuntu 14.04 , opencv 2.4.10 , QT 4.8.6

**Comment by benhoff** [comment]
Are you compiling opencv on your machine? Try running `make uninstall` in your build directory. You've hit the nail on the head with the problem though, you've got multiple instances of opencv installed and it's throwing your machine for a loop.

Might take a look at this as well. Disclaimer: I've never used this before :)
http://askubuntu.com/questions/87111/if-i-build-a-package-from-source-how-can-i-uninstall-or-remove-completely

**Comment by chfakht** [comment]
thanks instead ... the solution was : in the file camera.h you included 2 headers  so i have commented the second line because i have opencv 2.4.10

#include <opencv2/imgproc/imgproc.hpp>  /* for opencv 2.4.10 */ 
//#include <opencv2/imgcodecs.hpp>       /* for opencv 3.0.0  */

now the problem gone but i got another error :

faceDetector.cpp: In member function ‘void FaceDetector::process(cv::Mat)’:
faceDetector.cpp:76:78: error: no matching function for call to ‘QImage::QImage(const unsigned char*, int&, int&, cv::Mat::MStep&, QImage::Format, void (*)(void*), cv::Mat*)’
                        QImage::Format_RGB888, &matDeleter, new cv::Mat(frame));
                                                                              ^
faceDetector.cpp:76:78: note: candidates are:
In file included from /usr/include/qt4/QtGui/QImage:1:0,
                 from faceDetector.h:9,
                 from faceDetector.cpp:1:
/usr/include/qt4/QtGui/qimage.h:139:5: note: QImage::QImage(const QImage&)
     QImage(const QImage &);
     ^
/usr/include/qt4/QtGui/qimage.h:139:5: note:   candidate expects 1 argument, 7 provided
/usr/include/qt4/QtGui/qimage.h:136:14: note: QImage::QImage(const char*, const char*)
     explicit QImage(const char *fileName, const char *format = 0);
              ^
/usr/include/qt4/QtGui/qimage.h:136:14: note:   candidate expects 2 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:134:14: note: QImage::QImage(const QString&, const char*)
     explicit QImage(const QString &fileName, const char *format = 0);
              ^
/usr/include/qt4/QtGui/qimage.h:134:14: note:   candidate expects 2 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:132:14: note: QImage::QImage(const char* const*)
     explicit QImage(const char * const xpm[]);
              ^
/usr/include/qt4/QtGui/qimage.h:132:14: note:   candidate expects 1 argument, 7 provided
/usr/include/qt4/QtGui/qimage.h:129:5: note: QImage::QImage(const uchar*, int, int, int, QImage::Format)
     QImage(const uchar *data, int width, int height, int bytesPerLine, Format format);
     ^
/usr/include/qt4/QtGui/qimage.h:129:5: note:   candidate expects 5 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:128:5: note: QImage::QImage(uchar*, int, int, int, QImage::Format)
     QImage(uchar *data, int width, int height, int bytesPerLine, Format format);
     ^
/usr/include/qt4/QtGui/qimage.h:128:5: note:   candidate expects 5 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:127:5: note: QImage::QImage(const uchar*, int, int, QImage::Format)
     QImage(const uchar *data, int width, int height, Format format);
     ^
/usr/include/qt4/QtGui/qimage.h:127:5: note:   candidate expects 4 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:126:5: note: QImage::QImage(uchar*, int, int, QImage::Format)
     QImage(uchar *data, int width, int height, Format format);
     ^
/usr/include/qt4/QtGui/qimage.h:126:5: note:   candidate expects 4 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:125:5: note: QImage::QImage(int, int, QImage::Format)
     QImage(int width, int height, Format format);
     ^
/usr/include/qt4/QtGui/qimage.h:125:5: note:   candidate expects 3 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:124:5: note: QImage::QImage(const QSize&, QImage::Format)
     QImage(const QSize &size, Format format);
     ^
/usr/include/qt4/QtGui/qimage.h:124:5: note:   candidate expects 2 arguments, 7 provided
/usr/include/qt4/QtGui/qimage.h:123:5: note: QImage::QImage()
     QImage();
     ^
/usr/include/qt4/QtGui/qimage.h:123:5: note:   candidate expects 0 arguments, 7 provided
make: *** [faceDetector.o] Error 1

thanks :)

**Comment by benhoff** [comment]
Looks like the API for QImage was extended in Qt 5.4. 
If you look at the constructors in Qt 4.8 vs 5.4, there are a lot more options in Qt5 that I ended up using.

http://doc.qt.io/qt-4.8/qimage.html
http://doc.qt.io/qt-5/qimage.html

In order to use 4.8, you'd have to rewrite that conversion.
Glad you figured out the opencv 2 thing though :+1:

**Comment by chfakht** [comment]
There are 7 parameters in QT 5.4 instead of 5 parameters in QT 4.8 , so what i have did is to delete the last 2 parameters of the function QIMAGE , is that RIGHT ???
I have another error when compiling : auto changes meaning in c++11 please remove it  , so i enabled C++11 in Qt Creator by adding  QMAKE_CXXFLAGS += -std=c++11 in .pro file
All errors gone and now i'm running successfully the application 
thanks a lot

**Comment by benhoff** [comment]
Deleting out those last two parameters should work! Nicely done.
Not sure on the latest issue, though a google search reveals that you're not the only one.
http://stackoverflow.com/questions/21084991/vidioc-querymenu-invalid-argument
Do any of the answers help solve your issue?

**Comment by chfakht** [comment]
No i'm using opencv 2.4.10 and installed libqt4-dev but did not solve the problem , i will look in the code if i can change something 
is your program capable of detecting the eyes ?? because i saw that you are using haarcascade_eye.xml

i'm dreaming to code an algorithm that will be capable of detecting the eye direction , you are more experienced so can you advise me what algorithm can i use , i have found plenty of them .. 
please take a look to my post here http://answers.opencv.org/question/67113/algorithms-for-eye-gaze-eye-direction-in-opencv/  
Best regards

**Comment by benhoff** [comment]
See:
https://github.com/benhoff/opencv/blob/master/faceDetector.cpp#L59

The code is in there, but commented out. It's been awhile since I've messed with this library. Uncommenting those lines is likely not enough, but off the cuff I'm not sure what other work is needed to re-implement this functionality. I'm not sure about the best eye detection algorithm, but it sounds like a neat piece of functionality to add to this library! I'll do some research tonight and see what looks best given the current setup.

**Comment by chfakht** [comment]
Thanks a lot i will wait your response :) i will try some changes in the code and i will let you know :100:

**Comment by benhoff** [comment]
I've been pulled off on other stuff, but I'm going to close this issue for now as I don't have time budgeted to work on it :)
