### ISSUE TITLE
QImage

### ISSUE THREAD

**Issue by Ahleroy** [benhoff/face-recognizer-gui#9]
I have an error in faceDetector.cpp on line 75. 

error: no matching function for call to 'QImage::QImage(const uchar*, int&, int&, cv::MatStep&, QImage::Format, void (*)(void*), cv::Mat*)'
     const QImage image((const uchar *)frame.data, frame.cols, frame.rows, frame.step, QImage::Format_RGB888, &matDeleter, new cv::Mat(frame));

I havn't found where the problem comes from :/ Any idea ? :)

**Comment by benhoff** [comment]
What version of Qt are you compiling against? I used 5.4, I believe. I know the invocation call I used was new to Qt5 and not in Qt5. You might try looking through this issue https://github.com/benhoff/face-recognizer-gui/issues/6 if you're stuck with Qt4. I believe the person was able to get it to compile with Qt4 by making some changes.

**Comment by benhoff** [comment]
*not in Qt4

**Comment by Ahleroy** [comment]
You are right, my version of Qt was obsolete. It works perfectly fine on my other computer. Thank you, I should have seen that before.

**Comment by benhoff** [comment]
No worries, glad it's working for you!
